import { useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { createTicket, loadTickets, signIn, signOut, updateTicket } from './sharepoint'
import type { Analyst, Status, Ticket } from './sharepoint'
import './App.css'

const analysts = ['Diego','Miguel','Rony'] as const
const adminEmails = ['dmontoya@dichter-neira.com']
const catalog:Record<string,string[]>={
  'BOLIVIA':['P&G'],'CHILE':['COCA COLA (KO TRD)'],'COLOMBIA':['NESTLE (DSD)','NESTLE (ISD)','NESTLE (UTT)','SAMSUNG','COCA COLA (KO MD)-PLANOGRAMA','COCA COLA (KO MD)'],'COSTA RICA':['CARGILL','COCA COLA (KO MD)','COCA COLA (KO TRD)','FIFCO MOD','FIFCO TRD','NESTLE','P&G'],'ECUADOR':['CBC - EC','COCA COLA (KO TRD)','P&G','CBC EC','P&G_SC'],'EL SALVADOR':['COCA COLA (KO MD)','COCA COLA (KO TRD)','NESTLE','P&G','CERVECERIA','ABI CRECE'],'GUATEMALA':['CBC - GM','COCA COLA (KO MD)- ABVO','COCA COLA (KO MD)- EMBO','COCA COLA (KO TRD)- ABVO','COCA COLA (KO TRD)- EMBO','NESTLE','P&G','CBC GT'],'HONDURAS':['COCA COLA (KO MD)','COCA COLA (KO TRD)','NESTLE','P&G','CERVECERIA','ABI CRECE','CBC - HN'],'NICARAGUA':['COCA COLA (KO MD)','COCA COLA (KO TRD)','NESTLE','P&G'],'PANAMA':['COCA COLA (KO MD)','COCA COLA (KO TRD)','HEINEKEN','NESTLE','P&G','REPRICO'],'PARAGUAY':['P&G'],'PERU':['ABI','ABI DAS','GLORIA','LINDLEY','STOREVIEW ABI PERU','STOREVIEW MD IRT ABI PERU','CBC MYSTERY','GLORIA SV TRADICIONAL','GLORIA SC TRADICIONAL','AJE','Lindley - Auditor'],'REPUBLICA DOMINICANA':['COCA COLA (KO MD)','COCA COLA (KO TRD)','CORRIPIO','P&G','INDUVECA','PEPSI','INDUSTRIA SAN MIGUEL'],'URUGUAY':['P&G'],'VENEZUELA':['COCA COLA (KO TRD)']
}
const Logo=()=> <img className="logo" src="https://dichter-neira.com/wp-content/uploads/2026/06/Logo-nuevo-blanco-e1782489132302.webp" alt="dichter & neira"/>
const fmt=(date:string)=>new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(date))

export default function TicketApp(){
  const [view,setView]=useState<'new'|'admin'>('new'),[tickets,setTickets]=useState<Ticket[]>([]),[user,setUser]=useState<{name:string;email:string}|null>(null),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false)
  const enter=async()=>{setLoading(true);try{const person=await signIn();if(!adminEmails.includes(person.email.toLowerCase()))throw new Error('Tu cuenta no está autorizada para el panel interno.');setUser(person);setTickets(await loadTickets());setView('admin')}catch(error){setNotice(error instanceof Error?error.message:'No fue posible iniciar sesión.')}finally{setLoading(false)}}
  const update=async(ticket:Ticket,patch:Partial<Ticket>)=>{try{setLoading(true);await updateTicket(ticket,patch);setTickets(current=>current.map(x=>x.spId===ticket.spId?{...x,...patch}:x));setNotice('Cambio guardado. Power Automate notificará a las personas involucradas.')}catch(error){setNotice(error instanceof Error?error.message:'No se pudo guardar el cambio.')}finally{setLoading(false)}}
  return <main><header className="topbar"><button className="brand" onClick={()=>setView('new')}><Logo/><span>Centro de solicitudes</span></button><nav><button className={view==='new'?'active':''} onClick={()=>setView('new')}>Nueva solicitud</button><button className={view==='admin'?'active':''} onClick={()=>setView('admin')}>Área interna ↗</button></nav></header>{notice&&<div className="toast" role="status">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{view==='new'?<Request onCreated={ticket=>{setNotice(`Solicitud ${ticket.id} creada correctamente.`);setTickets([ticket,...tickets])}}/>:user?<Dash tickets={tickets} update={update} signOut={async()=>{await signOut();setUser(null);setTickets([])}}/>:<Login loading={loading} onLogin={enter}/>}</main>
}

function Request({onCreated}:{onCreated:(ticket:Ticket)=>void}){
  const [country,setCountry]=useState(''),[file,setFile]=useState<File|null>(null),[sending,setSending]=useState(false)
  const studies=useMemo(()=>catalog[country]||[],[country])
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSending(true);const data=new FormData(event.currentTarget);const ticket:Ticket={id:`DN-${Date.now().toString().slice(-6)}`,spId:'',created_at:new Date().toISOString(),requester_name:String(data.get('name')),requester_email:String(data.get('email')),country,study:String(data.get('study')),request_type:String(data.get('type')),detail:String(data.get('detail')),status:'Pendiente',assignee:'',attachment_name:file?.name};try{onCreated(await createTicket(ticket,file));event.currentTarget.reset();setCountry('');setFile(null)}catch(error){alert(error instanceof Error?error.message:'No fue posible crear la solicitud.')}finally{setSending(false)}}
  return <section className="request fade"><div className="hero"><div className="eyebrow">D&N · OPERACIONES</div><h1>Hagamos que tu<br/><em>solicitud avance.</em></h1><p>Centraliza tus requerimientos, adjunta tus insumos y recibe seguimiento claro en cada etapa.</p><div className="steps"><span><b>01</b> Ticket único</span><span><b>02</b> Seguimiento</span><span><b>03</b> Respuesta</span></div></div><form className="card" onSubmit={submit}><div className="intro"><i>01</i><div><h2>Nueva solicitud</h2><p>Ingresa con Microsoft al enviarla. Los campos con * son obligatorios.</p></div></div><div className="fields"><label>Nombre completo*<input name="name" required placeholder="Tu nombre"/></label><label>Correo corporativo*<input name="email" type="email" required placeholder="nombre@dichter-neira.com"/></label><label>País*<select value={country} onChange={event=>setCountry(event.target.value)} required><option value="">Selecciona un país</option>{Object.keys(catalog).map(item=><option key={item}>{item}</option>)}</select></label><label>Estudio*<select name="study" disabled={!country} required><option value="">{country?'Selecciona un estudio':'Primero elige un país'}</option>{studies.map(item=><option key={item}>{item}</option>)}</select></label><label>Tipo de solicitud*<select name="type" required><option value="">Selecciona el tipo</option>{['Muestra','Cotizaciones','Analisis','Otros'].map(item=><option key={item}>{item}</option>)}</select></label><label className="file">Insumo o archivo<input type="file" onChange={event=>setFile(event.target.files?.[0]||null)}/><span>{file?file.name:'Subir archivo · Excel, PDF, imagen...'}</span></label><label className="wide">Detalle de la solicitud*<textarea name="detail" required placeholder="Incluye el objetivo, alcance, período requerido y cualquier contexto que ayude al equipo."/></label></div><button className="primary" disabled={sending}>{sending?'Guardando...':'Enviar solicitud'} <b>→</b></button><small>La solicitud se guardará en SharePoint y las notificaciones serán gestionadas por Power Automate.</small></form></section>
}

function Login({loading,onLogin}:{loading:boolean;onLogin:()=>void}){return <section className="login fade"><div className="login-card"><div className="eyebrow">D&N · EQUIPO INTERNO</div><h1>Panel de <em>operaciones</em></h1><p>Accede con tu cuenta corporativa autorizada para gestionar las solicitudes comerciales.</p><button className="primary" disabled={loading} onClick={onLogin}>{loading?'Conectando...':'Ingresar con Microsoft'} <b>→</b></button><div className="hint">Tu acceso está protegido por Microsoft y los permisos de SharePoint.</div></div></section>}

function Dash({tickets,update,signOut}:{tickets:Ticket[];update:(ticket:Ticket,patch:Partial<Ticket>)=>void;signOut:()=>void}){
  const [filter,setFilter]=useState<'Todos'|Status>('Todos'),shown=tickets.filter(ticket=>filter==='Todos'||ticket.status===filter),done=tickets.filter(ticket=>ticket.status==='Finalizado').length,doing=tickets.filter(ticket=>ticket.status==='En proceso').length,count=(analyst:string)=>tickets.filter(ticket=>ticket.assignee===analyst).length
  return <section className="dash fade"><div className="dash-head"><div><div className="eyebrow">D&N · CONTROL DE OPERACIÓN</div><h1>Visión general</h1><p>Gestiona, asigna y da seguimiento a cada solicitud.</p></div><button className="ghost" onClick={signOut}>Cerrar sesión</button></div><div className="metrics"><Metric label="Solicitudes totales" value={tickets.length} note="Histórico visible"/><Metric label="En proceso" value={doing} note="Requieren seguimiento" color="yellow"/><Metric label="Finalizadas" value={done} note={`${tickets.length?Math.round(done/tickets.length*100):0}% de cierre`} color="green"/><Metric label="Tiempo promedio" value="—" note="Disponible al cerrar tickets" color="purple"/></div><div className="insights"><div className="analysts"><div className="eyebrow">Carga por analista</div>{analysts.map((analyst,index)=><div className="analyst" key={analyst}><i className={`a a${index}`}>{analyst[0]}</i><b>{analyst}</b><div className="bar"><span style={{width:`${tickets.length?count(analyst)/tickets.length*100:0}%`}}/></div><strong>{count(analyst)}</strong></div>)}</div><div className="completion"><div className="eyebrow">Ritmo de resolución</div><div className="ring"><b>{tickets.length?Math.round(done/tickets.length*100):0}%<small>finalizado</small></b></div><p>{done} de {tickets.length} solicitudes completadas</p></div></div><div className="panel"><div className="table-head"><div><h2>Solicitudes</h2><p>Actualiza el estado o asigna un responsable.</p></div><div className="filters">{(['Todos','Pendiente','En proceso','Finalizado'] as const).map(item=><button key={item} className={filter===item?'selected':''} onClick={()=>setFilter(item)}>{item}</button>)}</div></div>{shown.map(ticket=><article className="ticket" key={ticket.spId}><div className="id"><b>{ticket.id}</b><span>{fmt(ticket.created_at)}</span></div><div className="info"><div><i>{ticket.request_type}</i><b>{ticket.study} · {ticket.country}</b></div><p>{ticket.detail}</p><small>{ticket.requester_name} · {ticket.requester_email}{ticket.attachment_name&&` · 📎 ${ticket.attachment_name}`}</small></div><label className="select"><small>Estado</small><select value={ticket.status} onChange={event=>update(ticket,{status:event.target.value as Status})}><option>Pendiente</option><option>En proceso</option><option>Finalizado</option></select></label><label className="select"><small>Responsable</small><select value={ticket.assignee} onChange={event=>update(ticket,{assignee:event.target.value as Analyst})}><option value="">Sin asignar</option>{analysts.map(item=><option key={item}>{item}</option>)}</select></label><div className={`status ${ticket.status.replace(' ','-').toLowerCase()}`}>{ticket.status}</div></article>)}</div></section>
}
function Metric({label,value,note,color='' }:{label:string;value:string|number;note:string;color?:string}){return <div className={`metric ${color}`}><span>{label}</span><b>{value}</b><small>{note}</small></div>}
